<?php
/**
 * @file
 * Code for the  message subscribe email feature.
 */

/**
 * Implements hook_flag_access().
 *
 * @todo Flag access is broken. See https://www.drupal.org/node/2584647.
 */
function message_subscribe_email_flag_access($flag, $content_id, $action, $account) {
  if (strpos($flag->name, 'email_') === 0) {

    $entity_type = FLAG_API_VERSION == 3 ? $flag->entity_type : $flag->content_type;

    // Get the other flags on that same content.
    $user_flags = flag_get_user_flags($entity_type, $content_id, $account->uid);

    $name = str_replace('email_', '', $flag->name);
    // @FIXME
// // @FIXME
// // This looks like another module's variable. You'll need to rewrite this call
// // to ensure that it uses the correct configuration object.
// $prefix = variable_get('flag_prefix', 'subscribe') . '_';

    // Disable access to the flag when the subscribe flag is unflagged, but
    // allow unflagging.
    return $action == 'unflag' || !empty($user_flags[$prefix . $name]);
  }
}

/**
 * Implements hook_message_subscribe_get_subscribers_alter().
 *
 * Filters out subscribes to show only email subscribers.
 */
function message_subscribe_email_message_subscribe_get_subscribers_alter(array &$uids, array $values) {
  if (empty($uids)) {
    // Nobody is subscribed to the content.
    return;
  }

  /** @var \Drupal\flag\FlagInterface[] $flags */
  if (!$flags = \Drupal::service('message_subscribe_email.manager')->getFlags()) {
    // No subscribe email related flags.
    return;
  }

  $flag_ids = array();
  foreach ($flags as $flag) {
    $flag_ids[] = $flag->id();
  }

  $query = db_select('flagging', 'f');
  $result = $query->fields('f', array('uid'))
    ->condition('flag_id', $flag_ids, 'IN')
    ->condition('uid', array_keys($uids), 'IN')
    ->groupBy('uid')
    ->execute()
    ->fetchAll();

  foreach ($result as $row) {
    // Add 'email' to the list of notifiers.
    $uids[$row->uid]['notifiers']['email'] = 'email';
  }
}
