<?php
/**
 * @file
 * Code for the Message subscribe test feature.
 */

include_once 'message_subscribe_test.features.inc';
/**
 * @file
 *
 * message_subscribe_test.module
 */

/**
 * Implements hook_node_insert().
 */
function message_subscribe_test_node_insert($node) {
  if (!og_is_group_content_type('node', $node->type)) {
    // This is not a group content. Return early.
    return;
  }

  $node_wrapper = entity_metadata_wrapper('node', $node);

  $message = message_create('message_subscribe_example_og_post_in_group', array('uid' => $node->uid));
  $wrapper = entity_metadata_wrapper('message', $message);
  $wrapper->field_node_ref->set($node);
  $wrapper->field_node_groups_ref->set($node_wrapper->{OG_AUDIENCE_FIELD}->value(array('identifier' => TRUE)));
  message_subscribe_send_message('node', $node, $message);
}
